### ISSUE TITLE
Realizar las historias de usuario

### ISSUE THREAD

**Issue by Samuel150** [JohnatanCandy/JohnatanCandy#12]
<b>Como</b> Equipo
<b>Queremos</b> Realizar las historias de usuario del desarrollo
<b>Para</b> Dividir las tareas a realizar en cada Sprint

<b>Criterios de aceptación</b>
- [x] Historias de usuario terminadas

**Comment by JoaquinVM** [comment]
https://docs.google.com/document/d/1j8O4dg3EJHyvnhHNsmays4y0WoR2QGanUrLxAsWUPzg/edit?usp=sharing
