### ISSUE TITLE
Definir requerimientos funcionales y no funcionales

### ISSUE THREAD

**Issue by JoaquinVM** [JohnatanCandy/JohnatanCandy#14]
**Como** Equipo
**Quiero** Definir requerimientos del sistema
**Para** Decidir como implementarlo

**Criterios de aceptación**

- [x] Requerimientos definidos

**Comment by Samuel150** [comment]
Requerimientos Funcionales y no Funcionales
Drive: https://drive.google.com/open?id=1orhbtYSrxkewaEezJs95aTA98MMoVdXy
Descarga:
[ProyIngSoft-Req_(not)func.pdf](https://github.com/JonhatanCandy/JonhatanCandy/files/3872077/ProyIngSoft-Req_.not.func.pdf)

**Comment by Samuel150** [comment]
![Requerimientos](https://user-images.githubusercontent.com/31657526/69630793-a49eed00-1023-11ea-9e2b-19025b6884a8.JPG)

**Comment by Samuel150** [comment]
![Requerimientos](https://user-images.githubusercontent.com/31657526/69631882-c2208680-1024-11ea-803d-3a3c3d3d0ba0.JPG)
