### ISSUE TITLE
Realizar los casos de uso (Flujo)

### ISSUE THREAD

**Issue by Samuel150** [JohnatanCandy/JohnatanCandy#18]
<b>Como</b> Equipo
<b>Queremos</b> Diseñar el flujo del sistema
<b>Para</b> Conocer como se navegara por el sistema

<b>Criterios de aceptación</b>

- [x]  Realizar el diargrama

**Comment by Mendez9896** [comment]
https://drive.google.com/drive/folders/15WmrySyYuPYmOJ5bGhLgUtiDzQcqf1iA?usp=sharing

**Comment by Samuel150** [comment]
![Diagrama de Fjujo Admin](https://user-images.githubusercontent.com/31657526/69677353-1e14fa80-1079-11ea-89ad-35ba80b0b915.png)
![Diagrama de Fjujo Usuario](https://user-images.githubusercontent.com/31657526/69677354-1e14fa80-1079-11ea-8ece-7feab4798a65.png)
