### ISSUE TITLE
Crear Base de Datos

### ISSUE THREAD

**Issue by JoaquinVM** [JohnatanCandy/JohnatanCandy#22]
<b>Como</b> Equipo
<b>Queremos</b> Crear la base de datos
<b>Para</b> Guardar la información de usuarios y bienes

<b>Criterios de aceptación </b>
- [x] Existen una tabla para usuarios y otra para bienes.
- [x] Cada tabla cuanta con las columnas detalladas en el diagrama.
- [x] El id de cada fila se genera automáticamente con cada INSERT.
- [x] Las llaves foráneas están configuradas.

**Comment by Rodrixkill** [comment]
La base de datos funciona correctamente

**Comment by Mendez9896** [comment]
Aumentar tipo de usuario
