### ISSUE TITLE
Configurar base de datos

### ISSUE THREAD

**Issue by JoaquinVM** [JohnatanCandy/JohnatanCandy#23]
<b>COMO</b> DESARROLLADOR
<b>QUIERO</b> GUARDAR INFORMACION SOBRE BIENES-USUARIOS
<b>PARA</b> LA PÀGINA WEB PUEDA TENER DATOS ACTUALIZADOS

<b></b>
- [x] LA CONEXIÒN A LA BASE DE DATOS FUNCIONA CORRECTAMENTE.
- [ ] SE LOGRA PROBAR LA INSERCIÒN Y MODIFICACIÒN DE BIENES.
- [ ] SE LOGRA PROBAR LA CREACIÒN DE USUARIOS.

**Comment by Rodrixkill** [comment]
te falta la seccion de criterios de aceptacion
