### ISSUE TITLE
Realizar Página Log In

### ISSUE THREAD

**Issue by Samuel150** [JohnatanCandy/JohnatanCandy#24]
<b>Como</b> Usuario y Administrador
<b>Queremos</b> Entrar a la pagina de log in
<b>Para</b> Poder poder acceder a las funcionalidades del sistema

<b>Criterios de aceptación</b>

- [x] Se deben ingresar datos en usuario y contraseña, caso contrario se debe mostrar una alerta

**Comment by Samuel150** [comment]
Que les parece chicos?

**Comment by Rodrixkill** [comment]
Me parece muy buena la pagina faltaria solo la conexion con el backend?

**Comment by Mendez9896** [comment]
Todo bien
