### ISSUE TITLE
Menu de Navegacion

### ISSUE THREAD

**Issue by JoaquinVM** [JohnatanCandy/JohnatanCandy#27]
**TITLE:** MENU DE NAVEGACION
**DESCRIPTION:** MENU PARA NAVEGAR POR LA APLICACION
**COMO** [ USUARIO ADMINISTRADOR ]
**QUIERO** [ TENER UN MENU DE NAVEGACION ]
**PARA QUE**  [ NAVEGAR FACILMENTE POR LA APLICACION  ]

**CRITERIOS DE ACEPTACIÓN**
- [x] EL MENU ESTA UBICADO EN LA PARTE IZQUIERDA
- [x] SE PUEDE REUTILIZAR EN TODAS LAS PAGINAS DE LA APLICACION

**Comment by Samuel150** [comment]
Por que no resaltan mis seleccion del menu (highlight)?

**Comment by Rodrixkill** [comment]
tienes que cambiar la clase del li a class="active"
