### ISSUE TITLE
Definir herramienta para realizar mock ups

### ISSUE THREAD

**Issue by Samuel150** [JohnatanCandy/JohnatanCandy#3]
<b>Como</b> Equipo
<b>Queremos</b> Definir una herramienta para realizar mock ups
<b>Para</b> Trabajar con esta herramineta en el diseño del sistema

<b>Criterios de aceptación</b>
- [x] Encontrar herramienta

**Comment by Mendez9896** [comment]
Se determino que se utilizara la herramienta Balsamiq para diseñar los Mock ups
