### ISSUE TITLE
Realizar Mock ups en herramienta definida

### ISSUE THREAD

**Issue by Samuel150** [JohnatanCandy/JohnatanCandy#4]
<b>Como</b> Equipo
<b>Queremos</b> Realizar los mock ups
<b>Para</b> Saber como será el sistema visualmente

<b>Criterios de aceptación</b>
- [x] Realizar mock ups

**Comment by Mendez9896** [comment]
https://drive.google.com/drive/folders/1ANvthRB0LoRtwyOvZslPfFR4KEq2XuxH?usp=sharing
