### ISSUE TITLE
Definir que tecnologias usar en front-end

### ISSUE THREAD

**Issue by hrnn** [JohnatanCandy/JohnatanCandy#5]
<b>Como</b> Equipo
<b>Queremos</b> Definir las tecnologías a usar en front-end
<b>Para</b> Mantener la misma estructura en el sistema

<b>Criterios de aceptación</b>
- [x] Insertar las tecnologías a usar

**Comment by JoaquinVM** [comment]
Las tecnologías que se utilizaran son: Javascript, HTML, CSS, Bootstrap
