### ISSUE TITLE
Definir que tecnologias en back-end

### ISSUE THREAD

**Issue by hrnn** [JohnatanCandy/JohnatanCandy#6]
<b>Como</b> Equipo
<b>Queremos</b> Definir las tecnologias a usar en back-end
<b>Para</b> Mantener la misma estructura en el sistema

<b>Criterios de aceptación</b>
- [x] Insertar las tecnologías a usar

**Comment by Rodrixkill** [comment]
Se planea utilizar librerias de javascript(como ser el jquery) combinado con angular o php para el uso de  bases de datos
