### ISSUE TITLE
Diseñar la arquitectura del proyecto

### ISSUE THREAD

**Issue by hrnn** [JohnatanCandy/JohnatanCandy#8]
<b>Como</b> Equipo
<b>Queremos</b> Diseñar la arquitectura del proyecto
<b>Para</b> Conocer como funcionara el programa

<b>Criterios de aceptación</b>
- [x] Realizar el diargrama

**Comment by JoaquinVM** [comment]
Arquitectura: https://drive.google.com/file/d/10ky2R4VJRAL9xHUUNwBvS6CqOgCcjW1l/view?usp=sharing

**Comment by JoaquinVM** [comment]
![arquitectura](https://user-images.githubusercontent.com/30187719/69504228-48d74580-0ef7-11ea-9a1c-11fa7066ccd5.JPG)
